apiVersion: v2
name: quarantine-wrapper
description: Generischer Quarantine-Wrapper v2 - app-agnostische isolierte Netzwerk-Umgebung mit Kyverno-basierter transparenter Proxy/CA-Injection
type: application
version: 2.0.1
appVersion: "2.0.0"
keywords:
  - quarantine
  - network-isolation
  - security
  - proxy
  - mitmproxy
  - kyverno
maintainers:
  - name: Andreas Braunmiller
