apiVersion: v2
name: quarantine-wrapper
description: Generischer Quarantine-Wrapper - isolierte Netzwerk-Umgebung fuer beliebige ArgoCD-Apps
type: application
version: 1.5.1
appVersion: "1.5.1"
keywords:
  - quarantine
  - network-isolation
  - security
  - proxy
  - mitmproxy
maintainers:
  - name: Andreas Braunmiller
