# ============================================================
# Test-App fuer Quarantine-Wrapper Verifizierung
# ============================================================
appName: test1

services:
  - name: web
    port: 8080
    hostname: p-test1-k8s.sparafucile.net
    authentik:
      enabled: false

egress:
  squidExtraDomains: []
  extraEgressRules: []

mitmproxy:
  enabled: true
  authentik:
    enabled: false

ca:
  enabled: true

helloWorld:
  enabled: true

authentik:
  enabled: false

cilium:
  l7Visibility: false
