# App-Namespace: Isolierte Workloads
# Sync-Wave -10: Muss VOR allen anderen Ressourcen existieren
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "quarantine-wrapper.appNamespace" . }}
  labels:
    {{- include "quarantine-wrapper.appLabels" . | nindent 4 }}
    network-zone: quarantine
    quarantine: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    quarantine.sparafucile.net/proxy-url: {{ include "quarantine-wrapper.proxyURL" . | quote }}
    quarantine.sparafucile.net/gw-namespace: {{ include "quarantine-wrapper.gwNamespace" . | quote }}
    quarantine.sparafucile.net/no-proxy: {{ include "quarantine-wrapper.noProxy" . | quote }}
    quarantine.sparafucile.net/ca-configmap: "mitmproxy-ca-cert"
---
# Gateway-Namespace: Proxy-Stack (Squid, mitmproxy, CA-Distribution)
# Sync-Wave -10: Muss VOR allen anderen Ressourcen existieren
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "quarantine-wrapper.gwNamespace" . }}
  labels:
    {{- include "quarantine-wrapper.gwLabels" . | nindent 4 }}
    network-zone: quarantine-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
